# k8s-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory-frontend
  namespace: product-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-inventory-frontend
  template:
    metadata:
      labels:
        app: product-inventory-frontend
    spec:
      containers:
        - name: frontend
          image: product-inventory-frontend:latest # change to your image
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_AUTH_API_URL
              value: http://pern-auth-service:5001/api
            - name: REACT_APP_DATA_API_URL
              value: http://pern-data-service:5002/api
---
apiVersion: v1
kind: Service
metadata:
  name: product-inventory-frontend
  namespace: product-inventory
spec:
  selector:
    app: product-inventory-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
