# k8s-auth.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pern-auth-service
  namespace: product-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pern-auth-service
  template:
    metadata:
      labels:
        app: pern-auth-service
    spec:
      containers:
        - name: auth
          image: mern-cloud-app-auth-service:latest # change to your image
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5001"
            - name: DB_HOST
              value: pern-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: pern_app
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              value: super-secret-jwt
            - name: JWT_EXPIRES_IN
              value: "1d"
---
apiVersion: v1
kind: Service
metadata:
  name: pern-auth-service
  namespace: product-inventory
spec:
  selector:
    app: pern-auth-service
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
